### ISSUE TITLE
Bank withdrawing via Search method fails to withdraw item

### ISSUE THREAD

**Issue by nschaa** [powbot/issues#1]
For items that are not directly visible from when bank is opened, these items are withdrawn by searching for them. It can search the item successfully, but fails to properly withdraw the item that it has successfully searched for. This error occurs 100% of the time, making it impossible to bank properly if required items are not directly visible.

**Comment by MichalTDev** [comment]
Just to add a bit more info.

This happens when the item that is wanting to be withdrawn is visible in the main bank widget. This widget is inaccessible but visible when the search overlay is active it seems. 
The search widget screen covers up the item, so therefore it tries to withdraw it but it can't as it is not actually visible or interactable.

Possible fix would be to check if the search widget is open (and ignore the main bank item array), and possibly check the first slot of the bank (where the item should be located if being searched for)

**Comment by Protoprize** [comment]
Just to add a bit more info.
This happens when the item that is wanting to be withdrawn is visible in the main bank widget. This widget is inaccessible but visible when the search overlay is active it seems. The search widget screen covers up the item, so therefore it tries to withdraw it but it can't as it is not actually visible or interactable.
Possible fix would be to check if the search widget is open (and ignore the main bank item array), and possibly check the first slot of the bank (where the item should be located if being searched for)

**Comment by constt** [comment]
Closing this as we now scroll
