### ISSUE TITLE
[BUG] Bank.withdraw(item,1) doesn't withdraw the good amount if a custom amount has been set to X (ex : 1000)

### ISSUE THREAD

**Issue by xpelch** [powbot/issues#200]
**Describe the bug**
Bank.withdraw(item,1) doesn't withdraw the good amount if a custom amount has been set to X (ex : 1000), in that case it seems to withdraw 10 items, it does the same thing with Amount.ONE

**To Reproduce/Line of code causing issue**

Set X value to 1000 in the Bank, then :

```
   if (Inventory.stream().name(ITEM).isEmpty()) {

            Bank.stream().name(ITEM).findAny().ifPresent(item -> {
                if (Bank.withdraw(item, 1)) {
                    Condition.wait(() -> Inventory.stream().name(ITEM).isNotEmpty(), 200, 10);
                }
            });

            return;
        }
```

**Expected behavior**
It should withdraw one item

**Emulator or device :**
 - Device/Emulator: [Bluestacks]
 - OS: [Android 11]
 - Arch: [ARM64]

**Comment by 5Henveru2** [comment]
This situation will happen when the default withdraw quantity is 10 or X, assuming that the default withdraw quantity for X starts with a 1.

The easiest solution to prevent this from happening is to use a filter for the MenuCommand so that the action **equals** "Withdraw-1", because by default it uses **contains**.  
```
            return item.click(menuCommand -> menuCommand != null && menuCommand.getAction().equals("Withdraw-1"));
```
**This unfortunately is not an option when using the Bank.withdraw methods, so it would need to be implemented on the client-side,**

You can also determine if this is going to occur using the Banking.withdrawModeQuantity() and Bank.withdrawXAmount() methods, and set the withdrawModeQuantity with the appropriate setter method to avoid this from happening.

**Comment by constt** [comment]
pushed fix to make the bank use equals instead of contains
