### ISSUE TITLE
[Daxwalker] Leaving Shilo Village gets stuck at Wooden Gates when attempting to leave

### ISSUE THREAD

**Issue by nschaa** [powbot/issues#202]
@ Elias
As discussed in DMs. It eventually corrects itself and can leave via Carts but as you said, best case would be to avoid this entirely.

To replicate error: Start inside Shilo Village and daxwalk to any tile outside shilo village (a location that won't trigger a quicker teleport method that is readily available to the player)

[log.txt](https://github.com/powbot/issues/files/10491861/log.txt)

**Comment by 5Henveru2** [comment]
I believe this issue is actually related to the logs being spammed:
```
[] [Dooms Toggle] Handling Interface: 579
[] [Dooms Toggle] Handling Interface: 475
[] [Dooms Toggle] Handling Interface: 565
[] [Dooms Toggle] Handling Interface: 574
[] [Dooms Toggle] Handling Interface: 580
[] [Dooms Toggle] Handling Interface: 572
[] [Dooms Toggle] Handling Interface: 560
```
The latest version of the walking api should resolve this issue unless a client update does first.  @constt  it seems that using valid checks is not sufficient for widgets./components, and so I added a visible check as well. 
https://github.com/powbot/walking-api/commit/cd3443c0a98958eedf1ffa22972ffb4b8909f17f

**Comment by 5Henveru2** [comment]
However I'll still take my acc over there when I'm off work later today and see if I can improve the handler (or if the handler behaves well with the above fix applied)

**Comment by nschaa** [comment]
Fixed
